apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customresources.custom.k8s.io
spec:
  group: custom.k8s.io
  names:
    kind: CustomResource
    listKind: CustomResourceList
    plural: customresources
    singular: customresource
    shortNames:
      - cr
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                schedule:
                  type: string
                  description: "Schedule for the custom resource"
                configuration:
                  type: object
                  additionalProperties: true
                  description: "Custom configuration for the resource"
              required:
                - schedule
      additionalPrinterColumns:
        - name: Schedule
          type: string
          jsonPath: .spec.schedule
