apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "custom-controller.fullname" . }}
  labels:
    {{- include "custom-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "custom-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "custom-controller.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "custom-controller.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --log-level={{ .Values.controller.logLevel }}
            - --workers={{ .Values.controller.workers }}
            - --resync-period={{ .Values.controller.resyncPeriod }}
            {{- if .Values.controller.leaderElection.enabled }}
            - --leader-elect=true
            - --leader-election-lease-duration={{ .Values.controller.leaderElection.leaseDuration }}
            - --leader-election-renew-deadline={{ .Values.controller.leaderElection.renewDeadline }}
            - --leader-election-retry-period={{ .Values.controller.leaderElection.retryPeriod }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
